version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: asset_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin834
      POSTGRES_DB: asset_management
    ports:
      - "5464:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: asset_backend
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: admin834
      PGDATABASE: asset_management
      PGHOST: postgres
      PGPORT: 5432
    ports:
      - "3066:3066"

  employee-asset:
    build: ./Employee-Asset
    container_name: asset_employee_ui
    ports:
      - "8081:80"
    depends_on:
      - backend

  hr-asset:
    build: ./HR-Asset
    container_name: asset_hr_ui
    ports:
      - "8082:80"
    depends_on:
      - backend

volumes:
  postgres_data:

